routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/questions', 'QuestionController')->except('show');

Route::get('/questions/{slug}','QuestionController@show')->name('questions.show');

Route::resource('/questions.answers','AnswerController')->only(['store','edit','update','destroy']);

Route::post('/answers/{answer}/accept','AcceptAnswerController')->name('answers.accept');

Route::post('/questions/{question}/favourites','FavouriteController@store')->name('questions.favourites');

Route::delete('/questions/{question}/favourites','FavouriteController@destroy')->name('questions.unfavourites');

app/Answer.php
<?php

namespace App;

use App\Question;
use App\User;
use Illuminate\Database\Eloquent\Model;

class Answer extends Model
{

    protected $fillable = ['body','user_id'];

    public function question(){
        return $this->belongsTo(Question::class);
    }

     public function user(){
        return $this->belongsTo(User::class);
    }

    public function getBodyHtmlAttribute(){
    	return \Parsedown::instance()->text($this->body);
    }

    public static function boot(){
    	parent::boot();

    	static::created(function($answer){
            $answer->question->increment('answers_count');
    	});

        static::deleted(function($answer){
            $answer->question->decrement('answers_count');
        });
    }

    public function getCreatedDateAttribute(){
    	return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute(){
        if($this->id===$this->question->best_answer_id){
            return 'vote-accepted';
        }
        return '';
    }

    public function getIsBestAttribute(){
        if($this->id===$this->question->best_answer_id){
            return true;
        }else{
            return false;
        }
    }
}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\Question;
use Illuminate\Http\Request;

class AnswerController extends Controller
{

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Question $question, Request $request)
    {
        $request->validate(['body'=>'required'],['body.required'=>'Answer cannot be empty']);

        $question->answers()->create([
            'body'=>$request->body,
            'user_id' => \Auth::id(),
        ]);

        return back()->with('success','Your answer has been submitted successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function edit(Question $question, Answer $answer)
    {
        $this->authorize('update',$answer);
        return view('answers.edit',compact(['question','answer']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function update(Question $question, Request $request, Answer $answer)
    {
        $this->authorize('update',$answer);

        $answer->update($request->validate(['body'=>'required']));

        return redirect()->route('questions.show',$question->slug)->with('success','Your answer has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Answer  $answer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Question $question, Answer $answer)
    {
        $this->authorize('delete',$answer);

        $answer->delete();

        return back()->with('success','Your answer has been removed');
    }
}

resources/views/answers/_create.blade.php
<div class="row mt-4">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="card-title">
          <h2>Your Answer</h2>
        </div>
        <hr>
        <form action="{{route('questions.answers.store',$question->id)}}" method="post">
          @csrf
          <div class="form-group">
            <textarea name="body" rows="7" class="form-control {{$errors->has('body') ? 'is-invalid':''}}">{{old('body')}}</textarea>
            @if($errors->has('body'))
              <div class="invalid-feedback">
                <strong>{{$errors->first('body')}}</strong> 
              </div>
            @endif
          </div>
          <div class="form-group">
            <button class="btn btn-lg btn-outline-primary">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/answers/_index.blade.php
<div class="row mt-4">
  <div class="col-md-12">
    <div class="card">
      <div class="card-body">
        <div class="card-title">
          <h2>{{ $answersCount }} Answers</h2>
        </div>
        <hr>

        @include('layouts._messages')

        @foreach ($answers as $answer)
          <div class="media">
            <div class="d-flex flex-column vote-controls">
              <a title="This answer is useful" class="vote-up">
               <i class="fas fa-caret-up fa-3x"></i>
              </a>
              <span class="votes-count">1230</span>
              <a title="This answer is not useful" class="vote-down off">
                <i class="fas fa-caret-down fa-3x"></i>
              </a>
              @can('accept', $answer)
                  <a   title="Mark this as the best answer" 
                       class="{{$answer->status}} mt-2"
                       onclick="event.preventDefault();
                              document.getElementById('accept-answer-{{$answer->id}}').submit();">
                    <i class="fas fa-check fa-2x"></i>
                  </a>
                    <form action="{{route('answers.accept',$answer->id)}}" method="post" id="accept-answer-{{$answer->id}}" style="display: none;">
                      @csrf
                    </form>
                    @else

                     @if ($answer->is_best)
                       <a title="The question owner accepted this answer as the best answer" class="{{$answer->status}} mt-2">
                         <i class="fas fa-check fa-2x"></i>
                       </a>
                     @endif

              @endcan
            </div>
            <div class="media-body">
              {!! $answer->body_html !!}
              <div class="row">
                <div class="col-4">
                  <div class="ml-auto">
                    @can('update',$answer)
                        <a href="{{route('questions.answers.edit',[$question->id,$answer->id])}}" class="btn btn-sm btn-outline-primary">Edit</a>
                    @endcan
                    @can('delete',$answer)
                        <form action="{{route('questions.answers.destroy',[$question->id,$answer->id])}}" method="post" class="form-delete">
                          @method('DELETE')
                          @csrf
                          <button type="submitted" class="btn btn-sm btn-outline-danger" onclick="return confirm('Are you sure you want to delete this Answer ?')">Delete</button>
                        </form>
                    @endcan
                  </div>
                </div>
                <div class="col-4"></div>
                <div class="col-4">
                  <span class="text-muted"> Answered {{$answer->created_date}}</span>
                  <div class="media mt-2">
                    <a href="#" class="pr-2"><img src="{{asset('images/user.png')}}" class="img-rounded" alt="" width= "30px" height="30px"></a>
                    <div class="media-body mt-1">
                      <a href="#">{{$answer->user->name}}</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <hr>
        @endforeach
      </div>
    </div>
  </div>
</div>

resources/views/answers/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="row mt-4">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <div class="card-title">
              <h1>Edititing answer for question: <strong>{{$question->title}}</strong></h1>
            </div>
            <hr>
            <form action="{{route('questions.answers.update',[$question->id,$answer->id])}}" method="post">
              @csrf
              @method('PATCH')
              <div class="form-group">
                <textarea name="body" rows="7" class="form-control {{$errors->has('body') ? 'is-invalid':''}}">{{old('body',$answer->body)}}</textarea>
                @if($errors->has('body'))
                  <div class="invalid-feedback">
                    <strong>{{$errors->first('body')}}</strong> 
                  </div>
                @endif
              </div>
              <div class="form-group">
                <button class="btn btn-lg btn-outline-primary">Update</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection